name: Release Build

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            goos: linux
            goarch: amd64
            ext: ""
          - runner: macos-latest
            goos: darwin
            goarch: amd64
            ext: ""
          - runner: macos-latest
            goos: darwin
            goarch: arm64
            ext: ""
          - runner: windows-latest
            goos: windows
            goarch: amd64
            ext: ".exe"
    runs-on: ${{ matrix.runner }}
    env:
      CGO_ENABLED: 1

    steps:
      - name: CheckoutCode
        uses: actions/checkout@v4

      - name: InstallWindowsToolchain
        if: matrix.runner == 'windows-latest'
        shell: pwsh
        run: |
          choco install --no-progress mingw

      - name: SetupGoEnvironment
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: BuildBinary
        shell: bash
        run: |
          mkdir -p dist
          go build -ldflags="-s -w" -o "dist/ctx_${{ matrix.goos }}_${{ matrix.goarch }}${{ matrix.ext }}" ./cmd/ctx

      - name: UploadArtifact
        uses: actions/upload-artifact@v4
        with:
          name: ctx-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: CheckoutCode
        uses: actions/checkout@v4

      - name: DownloadArtifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/raw

      - name: FlattenArtifacts
        run: |
          mkdir -p dist
          find dist/raw -type f -name 'ctx_*' -exec mv {} dist/ \;

      - name: GenerateChecksums
        run: |
          cd dist
          sha256sum ctx_* > checksums.txt

      - name: ExtractReleaseNotes
        run: |
          TAG_NAME=${{ github.ref_name }}
          sed -n "/## \[$TAG_NAME\]/,/(## \[v[0-9])/p" CHANGELOG.md | grep -v '^## \[' > release_notes.md

      - name: CreateGitHubRelease
        uses: softprops/action-gh-release@v2
        with:
          name: "CTX release ${{ github.ref_name }}"
          body_path: release_notes.md
          files: |
            dist/ctx_linux_amd64
            dist/ctx_darwin_amd64
            dist/ctx_darwin_arm64
            dist/ctx_windows_amd64.exe
            dist/checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
