name: Go Tests

on:
  pull_request:
    branches: [ master ]
    paths:
      - '**/*.go'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: CheckoutCode
        uses: actions/checkout@v4

      - name: SetupGoEnvironment
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: RunTests
        run: go test ./...
